### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by olegmdev** [ingelaro/incodeappintern#10]
https://github.com/ingelaro/incodeappintern/blob/15168555ad48aeb86d1734bc85fac5a0eef34a76/src/usercard/UsercardContainer.jsx#L15

Please take a look at binding strategies in React and their pros/cons.
Take thoughtfully this article https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1

Summary:

> The initialization of arrow functions in class properties are transpiled into the constructor.
> Arrow functions in class properties won’t be in the prototype and we can’t call them with super.
> Arrow functions in class properties are much slower than bound functions, and both are much slower than usual function.

**Comment by ingelaro** [comment]
Rebinded properly (I think...)
